// This file is automatically generated. Do not modify it manually.
// For more information, see https://firebase.google.com/docs/web/learn-more#config-object
import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCK3Zlz5letRcFVwgUaZEAyU6pXG43T-5M",
  authDomain: "studio-2172440773-e64ad.firebaseapp.com",
  projectId: "studio-2172440773-e64ad",
  storageBucket: "studio-2172440773-e64ad.appspot.com",
  messagingSenderId: "477462644110",
  appId: "1:477462644110:web:d5475bc0999aa669ced0df",
};

export function getFirebaseConfig() {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error('No Firebase configuration object provided.' + '\n' +
      'Add your web app\'s configuration object to src/firebase/config.ts');
  } else {
    return firebaseConfig;
  }
}
