// This file is automatically generated. Do not modify it manually.

export type SecurityRuleContext = {
    path: string;
    operation: 'get' | 'list' | 'create' | 'update' | 'delete';
    requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
    constructor(public context: SecurityRuleContext) {
        const op = context.operation.toUpperCase();
        const path = context.path;
        super(`FirestorePermissionError: Insufficient permissions for ${op} on ${path}`);
        this.name = 'FirestorePermissionError';
    }
}
