// This file is automatically generated. Do not modify it manually.
'use client';
import { FirebaseApp, getApp, getApps, initializeApp } from 'firebase/app';
import { Auth, getAuth, connectAuthEmulator } from 'firebase/auth';
import { Firestore, getFirestore, connectFirestoreEmulator } from 'firebase/firestore';
import { getFirebaseConfig } from '@/firebase/config';

import { 
    useAuth, 
    useUser,
    useFirebaseApp,
    useFirestore,
    FirebaseProvider
} from '@/firebase/provider';

import { useCollection } from '@/firebase/firestore/use-collection';
import { useDoc } from '@/firebase/firestore/use-doc';
import { FirebaseClientProvider } from './client-provider';

let app: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

function initializeFirebase() {
    const firebaseConfig = getFirebaseConfig();
    if (!getApps().length) {
        app = initializeApp(firebaseConfig);
        auth = getAuth(app);
        firestore = getFirestore(app);
    } else {
        app = getApp();
        auth = getAuth(app);
        firestore = getFirestore(app);
    }

    return { app, auth, firestore };
}

export {
    initializeFirebase,
    FirebaseProvider,
    FirebaseClientProvider,
    useUser,
    useFirebaseApp,
    useFirestore,
    useAuth,
    useCollection,
    useDoc,
};
